create category bug
ctc-uci/abound-food-care-frontend pull request #146
Opened 2022-07-30 18:43 UTC by ctc-devops

After creating an event, the new event shows up under "All Events" but doesn't get mapped to the correct category label when you view it in the Events Dashboard (aka `/events`).

We should investigate this because I have a feeling it affects volunteers not being able to see the events too. Some theories I have about the root cause are the backend event category enum not categorizing events properly or the frontend event dashboard not filtering them correctly when it fetches the events from the backend.

- Look into possible causes on frontend and/or backend and make the events properly map to the correct event type
- If you need to make a backend PR to fix stuff on the backend, just go ahead and make the PR and tag me and Claude to get it reviewed alongside this
closes #140

2022-07-30 20:44 UTC, heyitsmichellelin commented
### What changes are included in this PR?
Fixed remaining filter issues regarding the type of event (status already worked). Issue was related to case differences between compared values, the `type` parameter passed into the function that filters events was lowercase, but the event object attributes were uppercase and slightly different. Fix involved minor changes to compared values and using .toLowerCase on event object attributes.

We also verified that the Create Event functionality does work as intended. As long as address fields are entered correctly the event will be created. However, given some invalid inputs (such as zipcode), the event will not be created and will also give no feedback to the user.

### Instructions to test changes:
To test filter thoroughly, create a set of 6 events with each representing one of each type and status, and check all given filters. Ensure that all events tagged to a particular status are proper for their respective values.
`[Food Running | Upcoming] [Food Running | Past]`

`[Dist | Upcoming] [ Distribution | Past]`

`[Other | Upcoming] [Other | Past]`

### Images (if applicable)
Distribution Filter Image
![dist](https://user-images.githubusercontent.com/88558727/181848175-3865ae46-38d8-4d41-bc4c-9d647a0f59b4.PNG)
Food Running Filter Image
![food running](https://user-images.githubusercontent.com/88558727/181848201-b92efd34-ad17-4a62-8763-b33a937e8300.PNG)

2022-07-31 19:39 UTC, claudeisakeeb requested changes
This is good, just 1 comment.

@alanchangxyz I think it's fine to just merge these changes in and then pagination can be a new PR. Thoughts?

2022-07-31 19:39 UTC, claudeisakeeb commented on src/components/events/AdminEvents/AdminEvents.jsx
> +
remove comment

2022-07-31 23:29 UTC, claudeisakeeb approved these changes
Looks good.

At this point I'm ok with not having an enum for these event types but let's see what alan has to say

2022-07-31 23:29 UTC, claudeisakeeb commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      filteredEvents = filteredEvents.filter(event => event.eventType.toLowerCase() === type);
Can we actually change this to be more consistent with the other comparisons? ie change type to distribution

2022-08-01 08:49 UTC, alanchangxyz commented on src/components/events/AdminEvents/AdminEvents.jsx
> +    if (status === 'all') {
this is passable, but for future reference, a more concise way of doing this is:
```
const filteredEvents = {
"all": events,
"upcoming": events.filter(event => determineStatus(event.startDatetime) === 'upcoming',
"past": ...
};
return filteredEvents[status];
```

2022-08-01 08:51 UTC, alanchangxyz commented
> Looks good.
> 
> At this point I'm ok with not having an enum for these event types but let's see what alan has to say

Yeah enum would be nice but at this point functional is functional. We don't need to worry about it for now

2022-08-01 08:52 UTC, alanchangxyz commented
> This is good, just 1 comment.
> 
> @alanchangxyz I think it's fine to just merge these changes in and then pagination can be a new PR. Thoughts?

Separating it to new PR

2022-08-01 08:52 UTC, alanchangxyz commented
Ok this is officially LGTM. Merging

2022-08-01 08:53 UTC, merged