event pagination
ctc-uci/abound-food-care-frontend pull request #148
Opened 2022-08-03 03:19 UTC by ctc-devops

closes #147

2022-08-03 05:35 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log(eventCount);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-03 05:35 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-17 07:09 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log(eventStatusValue, eventTypeValue);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-17 07:09 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log(eventResponse);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-17 07:09 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +    console.log('filtered', filteredEvents);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-17 07:09 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +    console.log('filtered', filteredEvents);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-18 06:26 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log('below is eventresponse');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-27 18:55 UTC, heyitsmichellelin commented
### What changes are included in this PR?
- move event filtering to backend
- add pagination to events grid

### Instructions to test changes:
- Click on the events tab on the nav bar to go to the events page
- Make sure corresponding events appear for different combinations of the status and type filters
- Click on arrows at the bottom to make sure pagination only displays at most 6 items per page

### Images (if applicable
![Page 1 of all event types and all statuses](https://user-images.githubusercontent.com/90677583/187044256-4d1e8205-734c-42e0-8ad5-339887ab8e6d.png)
![Page 2 of all event types and all statuses](https://user-images.githubusercontent.com/90677583/187044264-2bf0c9fd-59c4-4582-8e9f-3cade445f18a.png)
)

2022-09-01 18:44 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log('from fetchAllEvents');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-01 18:44 UTC, ctc-devops commented on src/components/events/AdminEvents/AdminEvents.jsx
> +      console.log(eventStatusValue, eventTypeValue);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-09 03:40 UTC, claudeisakeeb requested changes
Looks fine,

Could you please make the page index reset to 1 every time a search is issued?

2022-09-29 01:04 UTC, claudeisakeeb approved these changes, later dismissed
noice

2022-10-19 05:41 UTC, merged