volunteer event signup
ctc-uci/abound-food-care-frontend pull request #153
Opened 2022-08-11 03:40 UTC by ctc-devops

- Basically the reason most of the views are duplicated from the user signup flow is because AFC design wants the volunteers to confirm their availability before signing up for the event. Just preload the values and have functionality to change it on the users + availability tables if they need to change it

- **This comes after #138  + #134 **

closes #142

2022-08-20 07:01 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(data);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(config);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(rowIndex, colIndex, curValue);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/components/event-sign-up/UploadForms.jsx
> +    console.log(res);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(res);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(waivers);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(uploadWaiverRes);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:01 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(payload);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(data);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(config);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    console.log(rowIndex, colIndex, curValue);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(res);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(waivers);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(uploadWaiverRes);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-20 07:10 UTC, ctc-devops commented on src/pages/EventSignUp.jsx
> +    console.log(payload);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-08-25 07:09 UTC, alanchangxyz requested changes

2022-08-25 07:09 UTC, alanchangxyz commented on src/util/utils.jsx
> +  if (values.english) {
if we're going to do multiple if loops let's do instead:

```
const languages = ['english', 'spanish', .... ];
return languages.filter(lang => values[lang]);
```
(i'm not actually sure if that specific condition works but theoretically something that involves filtering and doesn't do an if loop for every single language)

2022-08-25 07:09 UTC, alanchangxyz commented on src/App.jsx
> +                    // FIXME: can admins sign up for event?
i think they should be able to but the current admin signup flow doesn't really give us the info we need for that, can you consult w alex about this

2022-08-25 07:09 UTC, alanchangxyz commented on src/App.jsx
> +                    // FIXME: can admins sign up for event?
for the record i'll also say there's an argument to be made for not letting them sign up if we're not already collecting the info since it would take too much time for us to change the admin flow to accommodate it away from making other essential features, we have ~3 weeks left and this is on the lower tier of our worries for now

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +        if (available.length > 0) {
this if else loop can be shortened to a single ternary `dayArray.push(available.length > 0 ? 2 : 1)`, let's do that

edit: actually could we refactor this to a `forEach` if possible, the `for` loops with manual day/time indexing hurt lowkey

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    generateSeries(9, 17);
any reason why we chose these numbers in particular for the `generateSeries` params

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    if (value === 2) {
this if/else could probably be made into a ternary (and a single setAvailabilty statement enclosing it too)

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    switch (startMinutes) {
holy moly let's come up with a better way to write this (either with an object and referencing key-values in that object or just cleaning up this series of if loops in general)

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/event-sign-up/Availability.jsx
>    return (
if your function component is just a single return statement given those parameters you can just straight up use the `AvailabilityChart` component directly instead wherever you use this `Availability` component, this isn't too necessary i think given you just wrote a ~25 line wrapper that could've been done with a direct ~10 line use of the `AvailabilityChart`

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/event-sign-up/UploadForms.jsx
> +    await saveAs(data, `-waivers.zip`);
is there supposed to be something prepended to that `-waivers.zip` thing in the filename

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/events/event/EventPage/EventPage.jsx
> +      const waivers = eventResponse[0].waivers?.filter(waiver => {
eh now that i look at this a little more we can just check if there are waivers in the `eventResponse[0]` object and only if there are we run this bit of code (a simple if statement should be fine for both checks here)

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/events/event/EventPage/EventPage.jsx
> +    const { data } = await AFCBackend.get(`/volunteers/${cookies.get(cookieKeys.USER_ID)}`);
i'd wrap this whole block in a try catch with the err message consolelogged just in case the request fails if backend down/something else happens

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/events/event/EventPage/EventPage.jsx
> +    if (!signedUp) return;
yeah i'm a fan of writing fewer lines but let's just use the curly brackets for blocks anyways here so someone else doesn't get confused later

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/events/event/EventVolunteerList/EventVolunteerList.jsx
> +        let matchingVolunteer = volunteerData.find(volunteer => {
lines 33-38 can probably be shortened to:

`const matchingVolunteer = volunteerData.find(...) ?? {};`

the `??` operator checks if left side is null and if it is (aka `Array.find()` doesn't find anything matching) then it uses the right side value

2022-08-25 07:09 UTC, alanchangxyz commented on src/components/profile/ProfileAvailability.jsx
> +    const { data: res } = await AFCBackend.get(`/availability/${userId}`);
would wrap this in a try/catch too just in case backend goes boom

2022-08-27 20:24 UTC, ctc-devops commented on src/components/events/event/EventPage/EventPage.jsx
> +      console.log(e.message);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-09 04:15 UTC, claudeisakeeb approved these changes
nice

2022-09-09 04:15 UTC, claudeisakeeb commented on src/components/AvailabilityChart/AvailabilityChart.jsx
> +    generateSeries(9, 17);
@jrock-3 correct me if im wrong but this is because the workday is 9-5

2022-09-12 00:02 UTC, merged