admin-volunteer-view
ctc-uci/abound-food-care-frontend pull request #155
Opened 2022-08-12 16:21 UTC by ctc-devops

(start after #132 is merged; starts as part of M3 on 8/6)

Start populating the volunteer list (an admin view accessible by clicking **Volunteers** on the navbar) with volunteer data in the database, along with the ability to fuzzy search for volunteers ([fusejs](http://fusejs.io)) and [nice-to-have] filter by driving ability/age

![Figma](https://user-images.githubusercontent.com/45449494/182989122-90c2806d-052e-4b67-a9e7-9aac3a4fe880.png)

closes #149

2022-08-19 07:26 UTC, alanchangxyz requested changes
There shouldn't be a package-lock.json here because we're using yarn, not npm in this project; we should be making commands using `yarn` instead of `npm` so
- let's do away with the `package-lock.json` and
- replace it with an updated `yarn.lock` (auto from `yarn` command) if you added or removed any packages using yarn

Also some other minor comments/fixes, but the rest is good for now until we implement pagination in the next week
EDIT: Also pls change the PR title to be more descriptive of what got changed here LOL

2022-08-19 07:26 UTC, alanchangxyz commented on src/components/volunteer-database/Database.jsx
>  function Database({ handleHideDatabase }) {
arrow function this pls

2022-08-19 07:26 UTC, alanchangxyz commented on src/components/volunteer-database/ViewAdminCodes/ViewAdminCodes.jsx
> +import { React, useState, useEffect } from 'react';
uhhh what got changed here, if nothing let's revert this file change

2022-08-19 07:31 UTC, alanchangxyz commented
Also can y'all get to styling the page to look a little more like the [figma](https://www.figma.com/file/h85P5QFeMPJlRy9piBQQxH/Wireframes?node-id=1414%3A55561) as part of the changes 🥺 currently looks like this on my localhost
![image](https://user-images.githubusercontent.com/45449494/185567257-6b28b5f0-aaa0-4286-a2ab-f64858b94488.png)

2022-08-26 18:53 UTC, ctc-devops commented on src/components/volunteer-availabilities/HeatMap.jsx
> +    console.log('times', times);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-02 03:42 UTC, ctc-devops commented on src/components/volunteer-availabilities/HeatMap.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-02 03:42 UTC, ctc-devops commented on src/components/volunteer-availabilities/VolunteerAvailability.jsx
> +import { AFCBackend } from '../../util/utils';
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'AFCBackend' is defined but never used.

2022-09-02 05:55 UTC, ctc-devops commented on src/components/volunteer-availabilities/VolunteerAvailability.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-09-09 03:23 UTC, claudeisakeeb requested changes
Good job, this looks fine to me for the most part and as discussed offline I think there are no performance issues with using Ant's frontend pagination?

Just one thing:
Could you please make it so that the page index resets to 1 whenever a new search is issued?

2022-09-09 03:23 UTC, claudeisakeeb commented on src/components/volunteer-availabilities/HeatMap.jsx
> +    // console.log('times', times);
remove

2022-09-09 03:23 UTC, claudeisakeeb commented on src/components/volunteer-availabilities/HeatMap.jsx
> +    // console.log('generatedSeries', generatedSeries);
remove

2022-09-09 03:23 UTC, claudeisakeeb commented on src/components/volunteer-availabilities/HeatMap.jsx
> +    // console.log(series);
remove x2

2022-10-19 06:28 UTC, merged